app = 'generaldeterrence'
primary_region = 'syd'

[build]

[env]
  PORT = "3000"
  DATA_DIR = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "leaderboard_data"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
